---
version: '3'

services:

  server:
    build: .
    image: index.docker.io/oaklabs/component-oak-lights:${VERSION-latest}
    network_mode: host
    environment:
      - PORT=9100
    volumes:
      - ./src:/src/
    devices:
      # Change this to match your Oak Lights device
      - /dev/ttyACM0
